# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: trello_demo
      POSTGRES_USER: trello_demo
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trello_demo
      SPRING_DATASOURCE_USERNAME: trello_demo
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"